let clgName=new String("GuruNanak")
console.log(clgName.toLowerCase())
console.log(clgName.toUpperCase())
console.log(clgName.length)
console.log(clgName.startsWith("guru"))
console.log(clgName.startsWith("Guru"))
console.log(clgName.endsWith("nanak"))
console.log(clgName.endsWith("Nanak"))
console.log(clgName.includes("ruNa"))
console.log(clgName.repeat(3))
console.log(`hi now i am studying in ${clgName} `)
